name: Android Release Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 9.3.1

    - name: Generate Official Release Keystore
      run: |
        keytool -genkey -v -keystore release.keystore -storepass echoes2026 -alias echoesrelease -keypass echoes2026 -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Abrari Laviarsy,O=Echoes FM,L=Jakarta,C=ID"

    - name: Build and Sign Optimized Release APK
      run: gradle assembleRelease -Pandroid.injected.signing.store.file=${{ github.workspace }}/release.keystore -Pandroid.injected.signing.store.password=echoes2026 -Pandroid.injected.signing.key.alias=echoesrelease -Pandroid.injected.signing.key.password=echoes2026

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Echoes-App-Release-Final
        path: app/build/outputs/apk/release/*.apk
